#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

require_once 'config/database.php';

use Psy\Shell;

$shell = new Shell();
$shell->run();