#!/usr/bin/env php
<?php

define('BASE', __DIR__);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

require_once BASE  . '/config/database.php';



$application = new Application();

require_once __DIR__ . '/app/command/register.php';

$application->setDefaultCommand('list');

$application->run();