#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

define('BASE', __DIR__);

use Symfony\Component\Console\Application;

$application = new Application();

require_once __DIR__ . '/app/command/register.php';

$application->setDefaultCommand('list');

$application->run();